const errorDatosDocentes = {
  tipodocente: 'Nombre invalido',
  nombre: 'Nombre invalido',
  apellidoPaterno: 'Apellido Paterno invalido',
  apellidoMaterno: 'Apellido Materno invalido',
  tipoDocente: 'Seleccione un nivel',
  'persona.nombre': 'Nombre invalido',
  'persona.apellidoPaterno': 'Apellido paterno invalido',
  'persona.apellidoMaterno': 'Apellido materno invalido',
  asignaturasDocentes: 'Seleccione una asignatura',
  tipoContratacion: 'Seleccione un tipo de contratación',
  antiguedad: 'Antigüedad invalida',
  experiencias: 'Experiencia laboral invalida',
  formacion_1_nivelId: 'Seleccione un Nivel',
  formacion_1_nombre: 'Nombre invalido',
  formacion_1_documentoPresentado: 'Seleccione un documento',
  formacion_1_fechaGraduado: 'Seleccione una fecha',
  formacion_1_institucion: 'Institución no invalida',
  formacion_2_nivelId: 'Seleccione un Nivel',
  formacion_2_nombre: 'Nombre invalido',
  formacion_2_documentoPresentado: 'Seleccione un documento',
  formacion_2_fechaGraduado: 'Seleccione una fecha',
  formacion_2_institucion: 'Institución no invalida',
};

export default errorDatosDocentes;
